name: Conditional Workflow

on:
  workflow_dispatch:
    inputs:
      suite:
        description: 'Suite to run'
        required: false
        default: 'all'
  schedule:
    - cron: '0 12 * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: >
      github.event_name == 'schedule' ||
      (github.event_name == 'workflow_dispatch' &&
      (github.event.inputs.suite == 'suite1' || github.event.inputs.suite == 'all'))
    steps:
      - run: echo "Running Job 1"

  job2:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: >
      github.event_name == 'schedule' ||
      (github.event_name == 'workflow_dispatch' &&
      (github.event.inputs.suite == 'suite2' || github.event.inputs.suite == 'all'))
    steps:
      - run: echo "Running Job 2"

  job3:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: >
      github.event_name == 'schedule' ||
      (github.event_name == 'workflow_dispatch' &&
      (github.event.inputs.suite == 'suite1' || github.event.inputs.suite == 'suite2' || github.event.inputs.suite == 'all'))
    steps:
      - run: echo "Running Job 3 after required jobs"
